### ISSUE TITLE
Problem with collapsible gmxIconGroup with text at IE9-10

### ISSUE THREAD

**Issue by TheSntXel** [ScanEx/gmxControls#2]
If I use text icon instead of graphic icon then menu collapses before i can choose item in it.
Possible caused by this:
Line 140 at L.Control.gmxIconGroup.js
bg.width = bg.height = ICONSIZE;
Text has bigger width than graphic icon and user usually moving cursor at right part of icon.

**Comment by OriginalSin** [comment]
Done commit: 8e74578e7f5a9c304cb8c7e0bf037b10a7503cec
